//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteganoBlaze.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteganoBlaze.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _encoded.
        /// </summary>
        public static string _encoded {
            get {
                return ResourceManager.GetString("_encoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Steganography.
        /// </summary>
        public static string AboutSteganography {
            get {
                return ResourceManager.GetString("AboutSteganography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Decoding.
        /// </summary>
        public static string AudioDecoding {
            get {
                return ResourceManager.GetString("AudioDecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Encoding.
        /// </summary>
        public static string AudioEncoding {
            get {
                return ResourceManager.GetString("AudioEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio not encoded.
        /// </summary>
        public static string AudioNotEncoded {
            get {
                return ResourceManager.GetString("AudioNotEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Channel.
        /// </summary>
        public static string BChannel {
            get {
                return ResourceManager.GetString("BChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits.
        /// </summary>
        public static string Bits {
            get {
                return ResourceManager.GetString("Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits per sample.
        /// </summary>
        public static string BitsPerSample {
            get {
                return ResourceManager.GetString("BitsPerSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio corrupted.
        /// </summary>
        public static string CarrierAudioCorrupted {
            get {
                return ResourceManager.GetString("CarrierAudioCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier capacity.
        /// </summary>
        public static string CarrierCapacity {
            get {
                return ResourceManager.GetString("CarrierCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier format.
        /// </summary>
        public static string CarrierFormat {
            get {
                return ResourceManager.GetString("CarrierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image corrupted.
        /// </summary>
        public static string CarrierImageCorrupted {
            get {
                return ResourceManager.GetString("CarrierImageCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier usage.
        /// </summary>
        public static string CarrierUsage {
            get {
                return ResourceManager.GetString("CarrierUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking carrier....
        /// </summary>
        public static string CheckingCarrier {
            get {
                return ResourceManager.GetString("CheckingCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select carrier.
        /// </summary>
        public static string ChooseCarrier {
            get {
                return ResourceManager.GetString("ChooseCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select message.
        /// </summary>
        public static string ChooseMessage {
            get {
                return ResourceManager.GetString("ChooseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string Decode {
            get {
                return ResourceManager.GetString("Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded file.
        /// </summary>
        public static string DecodedFile {
            get {
                return ResourceManager.GetString("DecodedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding done in.
        /// </summary>
        public static string DecodingDoneIn {
            get {
                return ResourceManager.GetString("DecodingDoneIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding message....
        /// </summary>
        public static string DecodingMessage {
            get {
                return ResourceManager.GetString("DecodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing message.
        /// </summary>
        public static string DecompressingMessage {
            get {
                return ResourceManager.GetString("DecompressingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting message.
        /// </summary>
        public static string DecryptingMessage {
            get {
                return ResourceManager.GetString("DecryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string Encode {
            get {
                return ResourceManager.GetString("Encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded Audio.
        /// </summary>
        public static string EncodedAudio {
            get {
                return ResourceManager.GetString("EncodedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded Image.
        /// </summary>
        public static string EncodedImage {
            get {
                return ResourceManager.GetString("EncodedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding many bits will distort the carrier.
        /// </summary>
        public static string EncodingBitsWarning {
            get {
                return ResourceManager.GetString("EncodingBitsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding done in.
        /// </summary>
        public static string EncodingDoneIn {
            get {
                return ResourceManager.GetString("EncodingDoneIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding details.
        /// </summary>
        public static string EncodingInformation {
            get {
                return ResourceManager.GetString("EncodingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding message....
        /// </summary>
        public static string EncodingMessage {
            get {
                return ResourceManager.GetString("EncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting message....
        /// </summary>
        public static string EncryptingMessage {
            get {
                return ResourceManager.GetString("EncryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption password.
        /// </summary>
        public static string EncryptionPassword {
            get {
                return ResourceManager.GetString("EncryptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password if the message was additionally encrypted.
        /// </summary>
        public static string EnterPasswordIfEncrypted {
            get {
                return ResourceManager.GetString("EnterPasswordIfEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message compression error.
        /// </summary>
        public static string ErrorCompressingMessage {
            get {
                return ResourceManager.GetString("ErrorCompressingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message encoding error.
        /// </summary>
        public static string ErrorEncodingMessage {
            get {
                return ResourceManager.GetString("ErrorEncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message encryption error.
        /// </summary>
        public static string ErrorEncryptingMessage {
            get {
                return ResourceManager.GetString("ErrorEncryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier save error.
        /// </summary>
        public static string ErrorSavingCarrier {
            get {
                return ResourceManager.GetString("ErrorSavingCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message save error.
        /// </summary>
        public static string ErrorSavingMessage {
            get {
                return ResourceManager.GetString("ErrorSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G Channel.
        /// </summary>
        public static string GChannel {
            get {
                return ResourceManager.GetString("GChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Decoding.
        /// </summary>
        public static string ImageDecoding {
            get {
                return ResourceManager.GetString("ImageDecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Encoding.
        /// </summary>
        public static string ImageEncoding {
            get {
                return ResourceManager.GetString("ImageEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not encoded!.
        /// </summary>
        public static string ImageNotEncoded {
            get {
                return ResourceManager.GetString("ImageNotEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave field empty if encryption was not used.
        /// </summary>
        public static string LeaveEmptyIfNot {
            get {
                return ResourceManager.GetString("LeaveEmptyIfNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max carrier pixel count is.
        /// </summary>
        public static string MaxCarrierPixels {
            get {
                return ResourceManager.GetString("MaxCarrierPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max carrier size is.
        /// </summary>
        public static string MaxCarrierSize {
            get {
                return ResourceManager.GetString("MaxCarrierSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max message size is.
        /// </summary>
        public static string MaxMessageSize {
            get {
                return ResourceManager.GetString("MaxMessageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message compression.
        /// </summary>
        public static string MessageCompression {
            get {
                return ResourceManager.GetString("MessageCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message encryption.
        /// </summary>
        public static string MessageEncryption {
            get {
                return ResourceManager.GetString("MessageEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        public static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Audio.
        /// </summary>
        public static string OriginalAudio {
            get {
                return ResourceManager.GetString("OriginalAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Image.
        /// </summary>
        public static string OriginalImage {
            get {
                return ResourceManager.GetString("OriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match.
        /// </summary>
        public static string PasswordsMustMatch {
            get {
                return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel bits to encode.
        /// </summary>
        public static string PixelBitsToEncode {
            get {
                return ResourceManager.GetString("PixelBitsToEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Channel.
        /// </summary>
        public static string RChannel {
            get {
                return ResourceManager.GetString("RChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading image data....
        /// </summary>
        public static string ReadingImageData {
            get {
                return ResourceManager.GetString("ReadingImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bits to encode.
        /// </summary>
        public static string SampleBitsToEncode {
            get {
                return ResourceManager.GetString("SampleBitsToEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image data....
        /// </summary>
        public static string SavingImageData {
            get {
                return ResourceManager.GetString("SavingImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving message data....
        /// </summary>
        public static string SavingMessageData {
            get {
                return ResourceManager.GetString("SavingMessageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scattered encoding.
        /// </summary>
        public static string ScatteredEncoding {
            get {
                return ResourceManager.GetString("ScatteredEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a carrier, an image or audio file, in which the message will be hidden..
        /// </summary>
        public static string SelectingCarrier_1 {
            get {
                return ResourceManager.GetString("SelectingCarrier_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted image formats:.
        /// </summary>
        public static string SelectingCarrier_2 {
            get {
                return ResourceManager.GetString("SelectingCarrier_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted audio formats:.
        /// </summary>
        public static string SelectingCarrier_3 {
            get {
                return ResourceManager.GetString("SelectingCarrier_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size of the carrier file is 10 MB..
        /// </summary>
        public static string SelectingCarrier_4 {
            get {
                return ResourceManager.GetString("SelectingCarrier_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steganography.
        /// </summary>
        public static string Steganography {
            get {
                return ResourceManager.GetString("Steganography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
