//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SteganoBlaze.Shared.ResourceFiles {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("SteganoBlaze.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _encoded.
        /// </summary>
        public static string _encoded {
            get {
                return ResourceManager.GetString("_encoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SteganoBlaze.
        /// </summary>
        public static string AboutSteganoBlaze {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteganoBlaze is a steganography app that enables the user to hide any type of file (the message) inside an image or an audio file (the carrier) and later recover it..
        /// </summary>
        public static string AboutSteganoBlaze_1 {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSB steganography is used where the least significant bits of bytes containing the values of pixels or samples of the carrier are overwritten with bits of the message. The user decides how many bits are considered insignificant..
        /// </summary>
        public static string AboutSteganoBlaze_2 {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden files can be additionally protected with a password using the secure AES encryption algorithm..
        /// </summary>
        public static string AboutSteganoBlaze_3 {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All processing is done locally on the user&apos;s machine, neither the carrier nor the message is transmitted over the web..
        /// </summary>
        public static string AboutSteganoBlaze_4 {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made using the.
        /// </summary>
        public static string AboutSteganoBlaze_5 {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to technology and the.
        /// </summary>
        public static string AboutSteganoBlaze_6 {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to library..
        /// </summary>
        public static string AboutSteganoBlaze_7 {
            get {
                return ResourceManager.GetString("AboutSteganoBlaze_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Decoding.
        /// </summary>
        public static string AudioDecoding {
            get {
                return ResourceManager.GetString("AudioDecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Encoding.
        /// </summary>
        public static string AudioEncoding {
            get {
                return ResourceManager.GetString("AudioEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio not encoded.
        /// </summary>
        public static string AudioNotEncoded {
            get {
                return ResourceManager.GetString("AudioNotEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Channel.
        /// </summary>
        public static string BChannel {
            get {
                return ResourceManager.GetString("BChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits.
        /// </summary>
        public static string Bits {
            get {
                return ResourceManager.GetString("Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits per sample.
        /// </summary>
        public static string BitsPerSample {
            get {
                return ResourceManager.GetString("BitsPerSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio corrupted.
        /// </summary>
        public static string CarrierAudioCorrupted {
            get {
                return ResourceManager.GetString("CarrierAudioCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier capacity.
        /// </summary>
        public static string CarrierCapacity {
            get {
                return ResourceManager.GetString("CarrierCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier format.
        /// </summary>
        public static string CarrierFormat {
            get {
                return ResourceManager.GetString("CarrierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image corrupted.
        /// </summary>
        public static string CarrierImageCorrupted {
            get {
                return ResourceManager.GetString("CarrierImageCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier usage.
        /// </summary>
        public static string CarrierUsage {
            get {
                return ResourceManager.GetString("CarrierUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible channel value change.
        /// </summary>
        public static string ChannelValueChange {
            get {
                return ResourceManager.GetString("ChannelValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking carrier....
        /// </summary>
        public static string CheckingCarrier {
            get {
                return ResourceManager.GetString("CheckingCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select carrier.
        /// </summary>
        public static string ChooseCarrier {
            get {
                return ResourceManager.GetString("ChooseCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select message.
        /// </summary>
        public static string ChooseMessage {
            get {
                return ResourceManager.GetString("ChooseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string Decode {
            get {
                return ResourceManager.GetString("Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered file.
        /// </summary>
        public static string DecodedFile {
            get {
                return ResourceManager.GetString("DecodedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding.
        /// </summary>
        public static string Decoding {
            get {
                return ResourceManager.GetString("Decoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Decode&quot; button to begin the decoding process..
        /// </summary>
        public static string Decoding_1 {
            get {
                return ResourceManager.GetString("Decoding_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the message has been decoded successfully, it&apos;s details will be displayed in the &quot;Recovered file&quot; section..
        /// </summary>
        public static string Decoding_2 {
            get {
                return ResourceManager.GetString("Decoding_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Save&quot; button to save the recovered file..
        /// </summary>
        public static string Decoding_3 {
            get {
                return ResourceManager.GetString("Decoding_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding done in.
        /// </summary>
        public static string DecodingDoneIn {
            get {
                return ResourceManager.GetString("DecodingDoneIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding instructions.
        /// </summary>
        public static string DecodingInstructions {
            get {
                return ResourceManager.GetString("DecodingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding message....
        /// </summary>
        public static string DecodingMessage {
            get {
                return ResourceManager.GetString("DecodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing message.
        /// </summary>
        public static string DecompressingMessage {
            get {
                return ResourceManager.GetString("DecompressingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting message.
        /// </summary>
        public static string DecryptingMessage {
            get {
                return ResourceManager.GetString("DecryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode.
        /// </summary>
        public static string Encode {
            get {
                return ResourceManager.GetString("Encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded Audio.
        /// </summary>
        public static string EncodedAudio {
            get {
                return ResourceManager.GetString("EncodedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded Image.
        /// </summary>
        public static string EncodedImage {
            get {
                return ResourceManager.GetString("EncodedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the message fits inside the carrier, click the &quot;Encode&quot; button to begin the encoding process..
        /// </summary>
        public static string Encoding_1 {
            get {
                return ResourceManager.GetString("Encoding_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the message has been encoded successfully, click the &quot;Save&quot; button to save the encoded carrier..
        /// </summary>
        public static string Encoding_2 {
            get {
                return ResourceManager.GetString("Encoding_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding many bits will distort the carrier.
        /// </summary>
        public static string EncodingBitsWarning {
            get {
                return ResourceManager.GetString("EncodingBitsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding done in.
        /// </summary>
        public static string EncodingDoneIn {
            get {
                return ResourceManager.GetString("EncodingDoneIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding details.
        /// </summary>
        public static string EncodingInformation {
            get {
                return ResourceManager.GetString("EncodingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding instructions.
        /// </summary>
        public static string EncodingInstructions {
            get {
                return ResourceManager.GetString("EncodingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding message....
        /// </summary>
        public static string EncodingMessage {
            get {
                return ResourceManager.GetString("EncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding options.
        /// </summary>
        public static string EncodingOptions {
            get {
                return ResourceManager.GetString("EncodingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a the amount of bits of image pixel channels or audio samples which will be used to hide the message data..
        /// </summary>
        public static string EncodingOptions_1 {
            get {
                return ResourceManager.GetString("EncodingOptions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In image carriers, from 0 to 8 bits can be chosen separately for the Red, Green and Blue pixel channels..
        /// </summary>
        public static string EncodingOptions_2 {
            get {
                return ResourceManager.GetString("EncodingOptions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In audio carriers, the maximum number of sample bits to be used is determined by the resolution of the chosen audio file..
        /// </summary>
        public static string EncodingOptions_3 {
            get {
                return ResourceManager.GetString("EncodingOptions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoding information panel shows the capacity of the carrier using the currently chosen pixel/sample bit amount and the ratio of message size to that capacity..
        /// </summary>
        public static string EncodingOptions_4 {
            get {
                return ResourceManager.GetString("EncodingOptions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding the message on many bits can significantly degrade the carrier quality..
        /// </summary>
        public static string EncodingOptions_5 {
            get {
                return ResourceManager.GetString("EncodingOptions_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting message....
        /// </summary>
        public static string EncryptingMessage {
            get {
                return ResourceManager.GetString("EncryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption password.
        /// </summary>
        public static string EncryptionPassword {
            get {
                return ResourceManager.GetString("EncryptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the message was additionally encrypted, input the password. Otherwise leave the field empty..
        /// </summary>
        public static string EncryptionPassword_1 {
            get {
                return ResourceManager.GetString("EncryptionPassword_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password if the message was additionally encrypted.
        /// </summary>
        public static string EnterPasswordIfEncrypted {
            get {
                return ResourceManager.GetString("EnterPasswordIfEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message compression error.
        /// </summary>
        public static string ErrorCompressingMessage {
            get {
                return ResourceManager.GetString("ErrorCompressingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message encoding error.
        /// </summary>
        public static string ErrorEncodingMessage {
            get {
                return ResourceManager.GetString("ErrorEncodingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message encryption error.
        /// </summary>
        public static string ErrorEncryptingMessage {
            get {
                return ResourceManager.GetString("ErrorEncryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier save error.
        /// </summary>
        public static string ErrorSavingCarrier {
            get {
                return ResourceManager.GetString("ErrorSavingCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message save error.
        /// </summary>
        public static string ErrorSavingMessage {
            get {
                return ResourceManager.GetString("ErrorSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G Channel.
        /// </summary>
        public static string GChannel {
            get {
                return ResourceManager.GetString("GChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Decoding.
        /// </summary>
        public static string ImageDecoding {
            get {
                return ResourceManager.GetString("ImageDecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Encoding.
        /// </summary>
        public static string ImageEncoding {
            get {
                return ResourceManager.GetString("ImageEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not encoded!.
        /// </summary>
        public static string ImageNotEncoded {
            get {
                return ResourceManager.GetString("ImageNotEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave field empty if encryption was not used.
        /// </summary>
        public static string LeaveEmptyIfNot {
            get {
                return ResourceManager.GetString("LeaveEmptyIfNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max carrier pixel count is.
        /// </summary>
        public static string MaxCarrierPixels {
            get {
                return ResourceManager.GetString("MaxCarrierPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max carrier size is.
        /// </summary>
        public static string MaxCarrierSize {
            get {
                return ResourceManager.GetString("MaxCarrierSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max message size is.
        /// </summary>
        public static string MaxMessageSize {
            get {
                return ResourceManager.GetString("MaxMessageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message compression.
        /// </summary>
        public static string MessageCompression {
            get {
                return ResourceManager.GetString("MessageCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message encryption.
        /// </summary>
        public static string MessageEncryption {
            get {
                return ResourceManager.GetString("MessageEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        public static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded carrier format:.
        /// </summary>
        public static string MoreOptions_1 {
            get {
                return ResourceManager.GetString("MoreOptions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s efficiency and performance decreases the larger the ratio of message size to carrier capacity..
        /// </summary>
        public static string MoreOptions_10 {
            get {
                return ResourceManager.GetString("MoreOptions_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Chrome, Edge and Opera browsers, the WebP image format can be used for the encoded carrier. Otherwise the carrier will be saved as PNG..
        /// </summary>
        public static string MoreOptions_2 {
            get {
                return ResourceManager.GetString("MoreOptions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression:.
        /// </summary>
        public static string MoreOptions_3 {
            get {
                return ResourceManager.GetString("MoreOptions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message data can be additionally compressed. The efficiency of the compression depends on the message file format and the contents of the file..
        /// </summary>
        public static string MoreOptions_4 {
            get {
                return ResourceManager.GetString("MoreOptions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption:.
        /// </summary>
        public static string MoreOptions_5 {
            get {
                return ResourceManager.GetString("MoreOptions_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message data can be additionally encrypted with the fast and secure AES-GCM algorithm using an user provided password..
        /// </summary>
        public static string MoreOptions_6 {
            get {
                return ResourceManager.GetString("MoreOptions_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scattered encoding:.
        /// </summary>
        public static string MoreOptions_7 {
            get {
                return ResourceManager.GetString("MoreOptions_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message can be encoded in a normal mode in which pixels or samples are encoded sequentially from first to last, or in a scattered mode in which pixels or samples are encoded in a random order..
        /// </summary>
        public static string MoreOptions_8 {
            get {
                return ResourceManager.GetString("MoreOptions_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing the scattered mode can make the encoding less visible and harder to detect..
        /// </summary>
        public static string MoreOptions_9 {
            get {
                return ResourceManager.GetString("MoreOptions_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Audio.
        /// </summary>
        public static string OriginalAudio {
            get {
                return ResourceManager.GetString("OriginalAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Image.
        /// </summary>
        public static string OriginalImage {
            get {
                return ResourceManager.GetString("OriginalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match.
        /// </summary>
        public static string PasswordsMustMatch {
            get {
                return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel bits to encode.
        /// </summary>
        public static string PixelBitsToEncode {
            get {
                return ResourceManager.GetString("PixelBitsToEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Channel.
        /// </summary>
        public static string RChannel {
            get {
                return ResourceManager.GetString("RChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading image data....
        /// </summary>
        public static string ReadingImageData {
            get {
                return ResourceManager.GetString("ReadingImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bits to encode.
        /// </summary>
        public static string SampleBitsToEncode {
            get {
                return ResourceManager.GetString("SampleBitsToEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible sample value change.
        /// </summary>
        public static string SampleValueChange {
            get {
                return ResourceManager.GetString("SampleValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image data....
        /// </summary>
        public static string SavingImageData {
            get {
                return ResourceManager.GetString("SavingImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving message data....
        /// </summary>
        public static string SavingMessageData {
            get {
                return ResourceManager.GetString("SavingMessageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scattered encoding.
        /// </summary>
        public static string ScatteredEncoding {
            get {
                return ResourceManager.GetString("ScatteredEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting carrier.
        /// </summary>
        public static string SelectingCarrier {
            get {
                return ResourceManager.GetString("SelectingCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a carrier, an image or audio file, in which the message will be hidden..
        /// </summary>
        public static string SelectingCarrier_1 {
            get {
                return ResourceManager.GetString("SelectingCarrier_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted image formats:.
        /// </summary>
        public static string SelectingCarrier_2 {
            get {
                return ResourceManager.GetString("SelectingCarrier_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted audio formats:.
        /// </summary>
        public static string SelectingCarrier_3 {
            get {
                return ResourceManager.GetString("SelectingCarrier_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size of the carrier file is 10 MB..
        /// </summary>
        public static string SelectingCarrier_4 {
            get {
                return ResourceManager.GetString("SelectingCarrier_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a carrier, an image or audio file, in which the message is hidden..
        /// </summary>
        public static string SelectingCarrier_6 {
            get {
                return ResourceManager.GetString("SelectingCarrier_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting message.
        /// </summary>
        public static string SelectingMessage {
            get {
                return ResourceManager.GetString("SelectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a message which will be hidden inside the carrier..
        /// </summary>
        public static string SelectingMessage_1 {
            get {
                return ResourceManager.GetString("SelectingMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message can be any file with a maximum size of 5 MB..
        /// </summary>
        public static string SelectingMessage_2 {
            get {
                return ResourceManager.GetString("SelectingMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steganography.
        /// </summary>
        public static string Steganography {
            get {
                return ResourceManager.GetString("Steganography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steganography is the practice of concealing a message within another message or a physical object..
        /// </summary>
        public static string Steganography_1 {
            get {
                return ResourceManager.GetString("Steganography_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The advantage of steganography over cryptography alone is that the intended secret message does not attract attention to itself as an object of scrutiny..
        /// </summary>
        public static string Steganography_2 {
            get {
                return ResourceManager.GetString("Steganography_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plainly visible encrypted messages, no matter how unbreakable they are, arouse interest and may in themselves be incriminating in countries in which encryption is illegal..
        /// </summary>
        public static string Steganography_3 {
            get {
                return ResourceManager.GetString("Steganography_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whereas cryptography is the practice of protecting the contents of a message alone, steganography is concerned with concealing the fact that a secret message is being sent and its contents..
        /// </summary>
        public static string Steganography_4 {
            get {
                return ResourceManager.GetString("Steganography_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about steganography..
        /// </summary>
        public static string Steganography_5 {
            get {
                return ResourceManager.GetString("Steganography_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
